### ISSUE TITLE
OpenCV Error

### ISSUE THREAD

**Issue by MuhammadBilal848** [sujanshresstha/YOLOv9_DeepSORT#2]
PS F:\YOLOv9_DeepSORT\yolov9> python object_tracking.py --video 1
I0305 17:32:45.155957  7176 embedder_pytorch.py:69] MobileNetV2 Embedder for Deep Sort initialised
I0305 17:32:45.156957  7176 embedder_pytorch.py:70] - gpu enabled: False
I0305 17:32:45.156957  7176 embedder_pytorch.py:71] - half precision: False
I0305 17:32:45.156957  7176 embedder_pytorch.py:72] - max batch size: 16
I0305 17:32:45.156957  7176 embedder_pytorch.py:73] - expects BGR: True
I0305 17:32:45.248009  7176 deepsort_tracker.py:142] DeepSort Tracker initialised
I0305 17:32:45.248596  7176 deepsort_tracker.py:143] - max age: 50
I0305 17:32:45.248805  7176 deepsort_tracker.py:144] - appearance threshold: 0.2
I0305 17:32:45.248805  7176 deepsort_tracker.py:145] - nms threshold: OFF
I0305 17:32:45.248805  7176 deepsort_tracker.py:148] - max num of appearance features: None
I0305 17:32:45.248805  7176 deepsort_tracker.py:149] - overriding track class : No
I0305 17:32:45.248805  7176 deepsort_tracker.py:152] - today given : No
I0305 17:32:45.248805  7176 deepsort_tracker.py:153] - in-build embedder : Yes
I0305 17:32:45.249814  7176 deepsort_tracker.py:154] - polygon detections : No
Fusing layers... 
Model summary: 839 layers, 68669632 parameters, 0 gradients, 241.4 GFLOPs
Adding AutoShape...
Traceback (most recent call last):
  File "F:\YOLOv9_DeepSORT\yolov9\object_tracking.py", line 108, in <module>
    app.run(main)
  File "C:\Users\Phoen\anaconda3\envs\yolov9-deepsort\Lib\site-packages\absl\app.py", line 308, in run
    _run_main(main, args)
  File "C:\Users\Phoen\anaconda3\envs\yolov9-deepsort\Lib\site-packages\absl\app.py", line 254, in _run_main
    sys.exit(main(argv))
             ^^^^^^^^^^
  File "F:\YOLOv9_DeepSORT\yolov9\object_tracking.py", line 97, in main
    cv2.imshow('YOLOv9 Object tracking', frame)
  File "F:\YOLOv9_DeepSORT\yolov9\utils\general.py", line 1130, in imshow
    imshow_(path.encode('unicode_escape').decode(), im)
cv2.error: OpenCV(4.9.0) D:\a\opencv-python\opencv-python\opencv\modules\highgui\src\window.cpp:1272: error: (-2:Unspecified error) The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Cocoa support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script in function 'cvShowImage'

**Comment by MuhammadBilal848** [comment]
solved it using:

`pip uninstall opencv-python-headless -y`

`pip install opencv-python --upgrade`
